import json

unique_foods_from_df = ['Leche Liconsa', 
                        'Otra leche opción A', 
                        'Otra leche opción B',
                        'Otra leche opción C',
                        'Leche preparada de sabor (chocolate u otro sabor)',
                        'Agregado a la leche: Azúcar',
                        'Agregado a la leche: Chocolate u otro saborizante',
                        'Queso panela o fresco o cottage',
                        'Quesos madurados (chihuahua, manchego, gouda, etc.)',
                        'Yogur de vaso: a) Entero natural',
                        'Yogur de vaso: b) Entero con frutas',
                        'Yogur de vaso: c) Bajo en grasa o light natural o con fruta (vitalinea, alpura light, lala light, etc.)',
                        'Yogur para beber: a) Entero natural',
                        'Yogur para beber: b) Entero con fruta',
                        'Yogur para beber: c) Bajo en grasa o light natural o con fruta (vitalinea, activia 0%, Siluette)',
                        'Danonino o similar', 
                        'Yakult o similares', 
                        'Plátano', 
                        'Plátano frito',
                        'Jícama', 
                        'Naranja o mandarina', 
                        'Manzana o pera', 
                        'Melón o sandía',
                        'Guayaba',
                        'Mango', 
                        'Papaya', 
                        'Piña', 
                        'Toronja', 
                        'Fresa', 
                        'Uvas',
                        'Durazno/melocotón', 
                        'Frutas en almíbar', 
                        'Frutas cristalizadas o secas',
                        'Tortitas de verduras capeadas', 
                        'Jitomate',
                        'Hojas Verdes (acelgas, espinacas, quelites)', 
                        'Chayote', 
                        'Zanahoria',
                        'Calabacita', 
                        'Brócoli o coliflor', 
                        'Col', 
                        'Ejotes', 
                        'Elote', 
                        'Lechuga',
                        'Nopales', 
                        'Pepino', 
                        'Aguacate', 
                        'Chile poblano',
                        'Cebolla por ejemplo en ensaladas, antojitos, o comida rápida',
                        'Verduras envasadas como chícharo, zanahoria, champiñones y ejotes.',
                        'Verduras congeladas como chícharo, zanahoria, brócoli, coliflor, ejotes',
                        'Torta o sándwich con pan blanco', 
                        'Torta o sándwich con pan integral',
                        'Hamburguesa', 
                        'Pizza', 
                        'Hot dog', 
                        'Carne de puerco', 
                        'Carne de res',
                        'Carne de res seca (machaca)', 
                        'Longaniza o chorizo',
                        'Salchicha de puerco, pavo o combinado, jamón de puerco o pavo o mortadela (a parte de en torta, sándwich o hot dog)',
                        'Pollo a) Pierna, muslo o pechuga', 
                        'Pollo b) Ala, patas',
                        'Pollo c) Higadito o molleja', 
                        'Huevo a) Tibio o cocido',
                        'Huevo b) Frito, estrellado o revuelto', 
                        'Pescado fresco',
                        'Pescado seco (charalitos, bacalao)',
                        'Atún y sardina (en tomate, agua o aceite)',
                        'Algún marisco (camarón, ostiones, etc.)',
                        'Frijoles preparados en casa: a) De la olla',
                        'Frijoles preparados en casa: b) Refritos',
                        'Frijoles envasados o de lata: a) De la olla',
                        'Frijoles envasados o de lata: b) Refritos',
                        'Lenteja, garbanzo, haba amarilla o alubia', 
                        'Arroz guisado',
                        'Avena en hojuelas, amaranto natural o tostado', 
                        'Pan blanco',
                        'Pan integral', 
                        'Pan dulce (excepto donas y churros)',
                        'Donas y churros de panadería', 
                        'Galletas integrales', 
                        'Galletas saladas',
                        'Papas a) Cocida', 
                        'Papas b) Frita o tortita de papa',
                        'Cereal a) Chocolate (Chocozucaritas, chocokrispis)',
                        'Cereal b) Light/cuidado de la figura (Special K)',
                        'Cereal c) Hojuela endulzada (Zucaritas)',
                        'Cereal d) Básico (Corn Flakes, arroz inflado sin sabor)',
                        'Cereal e) Variedades (Apple jacks, honey smacks, corn pops)',
                        'Cereal f) Sabor a frutas (Froot loops)', 
                        'Cereal g) Fibra (All Bran)',
                        'Cereal h) Especialidades (Crusli)',
                        'Cereal i) Multi ingredientes (Extra)',
                        'Antojitos con vegetales como sopes, quesadillas, tlacoyos, gorditas, y enchiladas (NO TACOS): a) Sin freír',
                        'Antojitos con vegetales como sopes, quesadillas, tlacoyos, gorditas, y enchiladas (NO TACOS): b) Fritos',
                        'Antojitos con res, cerdo pollo, vísceras, etc como tacos, quesadillas, tlacoyos, enchiladas, gorditas: a) Sin freír',
                        'Antojitos con res, cerdo pollo, vísceras, etc como tacos, quesadillas, tlacoyos, enchiladas, gorditas: b) Fritos',
                        'Pozole (todos tipos)', 
                        'Tamal (todos tipos)',
                        'Atole de maíz a) Atole con agua o pozol',
                        'Atole de maíz b) Atole con leche (aparte de la reportada en el apartado de “Productos lácteos”)',
                        'Refresco Normal', 
                        'Refresco Dieta', 
                        'Café: a) Café sin azúcar',
                        'Café: b) Azúcar agregada al café',
                        'Café: c) Leche agregada al café (aparte de la reportada en el apartado de “Productos lácteos”)',
                        'Café: d) Sustituto de crema agregada al café',
                        'Té o infusión: a) Té sin azúcar',
                        'Té o infusión: b) Azúcar agregada al té', 
                        'Jugos naturales sin azúcar',
                        'Jugos naturales con azúcar', 
                        'Aguas de fruta natural con azúcar',
                        'Aguas de fruta natural sin azúcar',
                        'Bebidas o aguas de sabor industrializadas sin azúcar (incluyendo dietéticas como Clight, Be-light, etc.)',
                        'Bebidas o aguas de sabor industrializadas con azúcar (frutsi, bonafina.)',
                        'Néctares de frutas o pulpa de frutas industrializados con azúcar (boing, jumex)',
                        'Agua sola', 
                        'Bebidas alcohólicas', 
                        'Chocolate',
                        'Dulce (caramelos, paletas)', 
                        'Dulces enchilados (miguelitos, tamarindos)',
                        'Frituras (todos tipos, incluyendo cacahuates japoneses)',
                        'Paletas y dulces de malvavisco (paleta payaso, bubu-lu-bu)',
                        'Gelatina, flan', 
                        'Pastel o pay', 
                        'Helado, nieves y paletas de agua',
                        'Helado y paletas de leche', 
                        'Haba, \xa0garbanzo o lentejas como botana',
                        'Nuez, almendra, avellana, cacahuates, semilla de calabaza (pepita) o de girasol, pistache, piñón, etc.',
                        'Palomitas de maíz caseras, de microondas o del cine (Todos tipos, excepto acarameladas)',
                        'Pastelillos y donas industrializadas', 
                        'Galletas dulces (todos tipos)',
                        'Barras de cereal', 
                        'Caldo de pollo, res o verduras (sólo caldo)',
                        'Sopa o caldo con verduras', 
                        'Sopa de pasta a) Sopa caldosa',
                        'Sopa de pasta b) Sopa seca', 
                        'Crema de verduras', 
                        'Sopas instantáneas',
                        'Limón por ejemplo en ensaladas, caldos, o carnes',
                        'Cebolla por ejemplo en salsas, o caldillos (molida o entera)',
                        'Chiles frescos por ejemplo en salsas, tacos, guisados (molido o entero)',
                        'Chiles envasados o enlatados, por ejemplo en el sándwich, torta, guisados.',
                        'Chile seco por ejemplo en salsas, tacos, guisados (molido o entero)',
                        'Tomate verde y jitomate por ejemplo en salsas, tacos, o guisados (molido o entero)',
                        'Azúcar (a parte de la agregada a las bebidas, leche, té, café, agua de frutas) por ejemplo en fresas o plátanos con crema',
                        'Margarina', 
                        'Mantequilla', 
                        'Mayonesa', 
                        'Crema', 
                        'Manteca vegetal',
                        'Manteca animal (cerdo o pollo)',
                        'Sal o condimento con sal agregada a sus alimentos',
                        'Salsas y aderezos agregados a sus alimentos: a) Cátsup',
                        'Salsas y aderezos agregados a sus alimentos: b) Salsa picante para botana agregada a sus alimentos',
                        'Salsas y aderezos agregados a sus alimentos: c) Salsa de soya, salsa inglesa o sazonadores líquidos agregados a sus alimentos',
                        'Otra Leche A', 
                        'Otra Leche B', 
                        'Otra Leche C',
                        'Agreagado a la leche: Azúcar',
                        'Agreagado a la leche: Chocolate u otro saborizante',
                        'Yogur en vaso: Entero natural', 
                        'Yogur en vaso: Entero con frutas',
                        'Yogur en vaso: Bajo en grasa o light natural o con fruta (vitalínea, alpura light, lala light, etcétera)',
                        'Yogur para beber: Entero natural', 
                        'Yogur para beber: Entero con frutas',
                        'Yogur para beber: Bajo en grasa o light natural o con fruta (vitalínea, activia 0%, Siluette, etcétera)',
                        'Chile  poblano',
                        'Salchicha de puerco, pavo o combinado,  jamón de puerco o pavo  o mortadela (a parte de en torta, sándwich o hot dog)',
                        'Pollo: a) Pierna, muslo o pechuga', 
                        'Pollo: b) Alas, patas',
                        'Pollo: c) Higado o mollejas', 
                        'Huevo: a) Tibio o cocido',
                        'Huevo: b) Frito, estrellado o revuelto', 
                        'Papas: a) Cocida',
                        'Papas: b) Frita o tortita de papa',
                        'Cereal de caja: a) Chocolate (Chocozucaritas, chocokrispis)',
                        'Cereal de caja: b) Light/cuidado de la figura (Special K)',
                        'Cereal de caja: c) Hojuela endulzada (Zucaritas)',
                        'Cereal de caja: d) Básico (Corn Flakes, arroz inflado sin sabor)',
                        'Cereal de caja: e) Variedades (Apple jacks, honey smacks, corn pops)',
                        'Cereal de caja: f) Sabor a frutas (Froot loops)',
                        'Cereal de caja: g) Fibra (All Bran)',
                        'Cereal de caja: h) Especialidades (Crusli)',
                        'Cereal de caja: i) Multi ingredientes (Extra)',
                        'Antojitos con res, cerdo pollo, vísceras, etc como tacos, quesadillas, tlacoyos, enchiladas,  gorditas: a) Sin freír',
                        'Antojitos con res, cerdo pollo, vísceras, etc como tacos, quesadillas, tlacoyos, enchiladas,  gorditas: b) Fritos',
                        'Tamal  (todos tipos)',
                        'Atole de maíz  b) Atole con leche (aparte de la reportada en el apartado de “Productos lácteos”)',
                        'Haba, garbanzo o lentejas como botana', 
                        'Sopa de pasta: a) Sopa caldosa',
                        'Sopa de pasta: b) Sopa seca',
                        'Chile seco por ejemplo en salsas, tacos, guisados (molido  o entero)',
                        'Sal o condimento con sal  agregada a sus alimentos', 
                        'Leche materna',
                        'Atún y sardina (en tomate, aguo o aceite)', 
                        'Caldo de frijol']


foods = {}

with open('./Data/Inputs/food_category_data0.json', 'r',encoding='utf-8') as f:
    foods = json.load(f)

    for food in foods:
        foods[food]["moderacion"] = ""
        foods[food]["balance"] = ""
    
    for unique_food in unique_foods_from_df:
        if foods.get(unique_food) is None:
            foods[unique_food] = {
                "grupo" : "",
                "subgrupo" : "",
                "moderacion" : "",
                "balance" : ""
            }


with open('./Data/Inputs/food_category_data1.json', 'w',encoding='utf-8') as f:
    json.dump(foods, f, ensure_ascii=False, indent=4)

        
        
    